# .streamlit/secrets.toml
MONGODB_URI = "mongodb+srv://AHS_db_user:fAdp5LC8GglDRedl@ahs786student.qh8rsrb.mongodb.net/elhub?retryWrites=true&w=majority&tls=true&tlsDisableOCSPEndpointCheck=true&appName=AHS786Student"
